language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t iris77docker/docker-react-example -f Dockerfile.dev .

script: 
  - docker run -e CI=true iris77docker/docker-react-example npm run test -- -- coverage -- -- watchAll=false